export const ABILITY_DESCRIPTIONS: Record<string, string> = {
  'Flash Finality': 'Unblocked face attack destroys the strongest enemy creature',
  'Sandwich Attack': 'On play, steal 2 power from a random enemy creature',
  'Rug Pull': 'On death, deals base power to all enemies + half to face',
  'Diamond Hands': 'Immune to ability destruction — only dies in combat',
  'MEV Extract': '+1 power each turn. Snowballs if left unchecked',
  'Gas Optimization': 'Costs 1 less mana per creature you control',
  'Fork': 'Pay 2 mana to create a -1/-1 copy of this creature',
  'Liquidate': 'Destroy an enemy creature with less power than your toughness',
  '51% Attack': '+3/+3 if you control more creatures than your opponent',
  'Airdrop': 'On play, draw 2 cards',
  'Stake': 'Tap to permanently gain +1/+1. Can\'t attack while staked',
  'Bridge': 'No summoning sickness — can attack immediately',
  'Mempool': 'Pay 1 mana to lock an enemy\'s abilities for 2 turns',
  'Consensus': 'All your creatures get +1 power this turn',
  'Revert': 'Returns to hand instead of dying (once per game)',
  'Slippage': 'When attacked, the attacker loses 1 power permanently',
  'Block Reward': 'Gain 1 life when this creature blocks',
  'Parallel Execution': 'Can use abilities twice per turn',
  'Oracle': 'Look at the top 3 cards of your deck, pick one',
}
